"""Demo session export — save a completed demo run as HTML or Markdown.

Renders a list of turn dicts (``question``, ``answer``, ``strategy``,
``confidence``, ``reasoning_steps``, ``evidence``, ``entities``, etc.)
into a self-contained HTML page or a GitHub-flavoured Markdown document.
"""

from __future__ import annotations

import html as html_mod
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# HTML export
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>KG-RAG Demo Export</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; color: #222; }}
  h1   {{ border-bottom: 2px solid #4a90d9; padding-bottom: .3em; }}
  .turn {{ margin-bottom: 2rem; padding: 1rem; border: 1px solid #ddd; border-radius: 8px; }}
  .q    {{ font-weight: bold; color: #1a73e8; }}
  .a    {{ margin-top: .5em; white-space: pre-wrap; }}
  .meta {{ font-size: .85em; color: #666; margin-top: .4em; }}
  details {{ margin-top: .5em; }}
  summary {{ cursor: pointer; font-size: .9em; color: #555; }}
  table  {{ border-collapse: collapse; width: 100%; margin-top: .4em; }}
  th, td {{ text-align: left; padding: .3em .6em; border: 1px solid #ddd; }}
  th     {{ background: #f5f5f5; }}
</style>
</head>
<body>
<h1>KG-RAG Demo Export</h1>
{turns_html}
<footer style="margin-top:3rem;font-size:.8em;color:#999">Generated by KG-RAG Agent</footer>
</body>
</html>
"""


def _render_turn_html(idx: int, turn: dict[str, Any]) -> str:
    """Render a single Q&A turn to HTML."""
    q = html_mod.escape(str(turn.get("question", "")))
    a = html_mod.escape(str(turn.get("answer", "")))
    strategy = html_mod.escape(str(turn.get("strategy", "—")))
    confidence = turn.get("confidence")
    conf_str = f"{confidence:.0%}" if isinstance(confidence, (int, float)) else "—"

    parts = [
        f'<div class="turn">',
        f'<div class="q">Q{idx}: {q}</div>',
        f'<div class="a">{a}</div>',
        f'<div class="meta">Strategy: {strategy} &middot; Confidence: {conf_str}</div>',
    ]

    # Reasoning steps
    steps = turn.get("reasoning_steps") or []
    if steps:
        parts.append("<details><summary>Reasoning steps</summary><ol>")
        for s in steps:
            parts.append(f"<li>{html_mod.escape(str(s))}</li>")
        parts.append("</ol></details>")

    # Evidence
    evidence = turn.get("evidence") or []
    if evidence:
        parts.append("<details><summary>Evidence</summary><ul>")
        for ev in evidence:
            parts.append(f"<li>{html_mod.escape(str(ev))}</li>")
        parts.append("</ul></details>")

    # Entities
    entities = turn.get("entities") or []
    if entities:
        parts.append("<details><summary>Entities</summary><table>")
        parts.append("<tr><th>Label</th><th>Type</th></tr>")
        for ent in entities:
            label = html_mod.escape(str(ent.get("label", ent) if isinstance(ent, dict) else ent))
            etype = html_mod.escape(str(ent.get("entity_type", "") if isinstance(ent, dict) else ""))
            parts.append(f"<tr><td>{label}</td><td>{etype}</td></tr>")
        parts.append("</table></details>")

    parts.append("</div>")
    return "\n".join(parts)


def export_html(
    session_data: list[dict[str, Any]],
    output_path: str | Path = "data/demo_export.html",
) -> Path:
    """Export a demo session as a self-contained HTML file.

    Parameters
    ----------
    session_data:
        List of turn dicts — each should have at least ``question`` and
        ``answer`` keys.
    output_path:
        Destination file path.

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    turns_html = "\n".join(
        _render_turn_html(i + 1, t) for i, t in enumerate(session_data)
    )
    output_path.write_text(
        _HTML_TEMPLATE.format(turns_html=turns_html), encoding="utf-8"
    )
    logger.info("demo_export.html", path=str(output_path), turns=len(session_data))
    return output_path


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------


def export_markdown(
    session_data: list[dict[str, Any]],
    output_path: str | Path = "data/demo_export.md",
) -> Path:
    """Export a demo session as GitHub-flavoured Markdown.

    Parameters
    ----------
    session_data:
        List of turn dicts.
    output_path:
        Destination file path.

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = ["# KG-RAG Demo Export", ""]

    for i, turn in enumerate(session_data, 1):
        q = turn.get("question", "")
        a = turn.get("answer", "")
        strategy = turn.get("strategy", "—")
        confidence = turn.get("confidence")
        conf_str = f"{confidence:.0%}" if isinstance(confidence, (int, float)) else "—"

        lines.append(f"## Q{i}: {q}")
        lines.append("")
        lines.append(f"**Answer:** {a}")
        lines.append("")
        lines.append(f"| Strategy | Confidence |")
        lines.append(f"|----------|------------|")
        lines.append(f"| {strategy} | {conf_str} |")
        lines.append("")

        # Reasoning steps
        steps = turn.get("reasoning_steps") or []
        if steps:
            lines.append("<details><summary>Reasoning steps</summary>")
            lines.append("")
            for j, s in enumerate(steps, 1):
                lines.append(f"{j}. {s}")
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # Evidence
        evidence = turn.get("evidence") or []
        if evidence:
            lines.append("<details><summary>Evidence</summary>")
            lines.append("")
            for ev in evidence:
                lines.append(f"- {ev}")
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # Entities table
        entities = turn.get("entities") or []
        if entities:
            lines.append("<details><summary>Entities</summary>")
            lines.append("")
            lines.append("| Label | Type |")
            lines.append("|-------|------|")
            for ent in entities:
                if isinstance(ent, dict):
                    lines.append(f"| {ent.get('label', '?')} | {ent.get('entity_type', '')} |")
                else:
                    lines.append(f"| {ent} | |")
            lines.append("")
            lines.append("</details>")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("*Generated by KG-RAG Agent*")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("demo_export.markdown", path=str(output_path), turns=len(session_data))
    return output_path
